log:
  level: "INFO"
meshsight:
  api:
    url: "http://meshsight-gateway:80"
postgres:
  host: "meshplorer-postgres"
  port: "5432"
  database: "postgres"
  username: "postgres"
  password: "changeme"
bot:
  workChannells: # å·¥ä½œé »é“
    - key: 1PG7OiApB1nwvP+rz05pAQ==
      name: TestChannel
      id: 5
  devices: # è¨­å‚™
    - name: "abcd"
      type: "tcp"
      host: 192.168.0.201
  emergencyGuardian: # ç·Šæ€¥å®ˆè­·è€…
    channelName: "Emergency!" # ç·Šæ€¥å®ˆè­·è€…ç›£è½é »é“åç¨±
    channelKey: "1PG7OiApB1nwvP+rz05pAQ==" # ç·Šæ€¥å®ˆè­·è€…ç›£è½é »é“ key
    notifyChannelId: 5 # ç·Šæ€¥å®ˆè­·è€…é€šçŸ¥é »é“ id
  ignoreId: # å¿½ç•¥ä¾†è‡ªæŸ id çš„è¨Šæ¯
    - "0000000000"
mqtt:
  client:
    - hosts:
        - mqtt.meshtastic.org
      identifier: meshplorer-gateway
      password: large4cats
      port: 1883
      retryTime: 30
      showErrorLog: true
      topics:
        - msh/TW/#
      username: meshdev
cwa:
  key: "your-cwa-key"
adMessages:
  - "ğŸ¤–ä½¿ç”¨ @nfs.tw help æŸ¥çœ‹æŒ‡ä»¤ï¼"
  - "ğŸŒ¦ï¸æƒ³çŸ¥é“ä»Šå¤©ç©¿ä»€éº¼ï¼Ÿå«æˆ‘ä¸€è² @nfs.tw weatherï¼Œé¦¬ä¸Šå ±ä½ ç•¶åœ°å¤©æ°£ï¼ï¼ˆè¨˜å¾—é–‹å®šä½åˆ†äº«å–” ğŸ“ï¼‰"
  - "ğŸ—ºï¸æ‰¾é™„è¿‘ç¯€é»ï¼Ÿå¿«ä¸Š MeshSight æ¢ç´¢èµ·ä¾†å§ ğŸ” https://meshsight.nfs.tw/"
  - "ğŸ§­æˆ‘æ˜¯ MeshPlorerï¼Œä¸€åç©¿æ¢­æ–¼ Meshtastic ç¶²è·¯ä¸­çš„æ¢ç´¢è€…ï¼"
dify:
  api:
    base: "https://api.dify.ai/v1"
    key: "your-dify-key"
